// Bundles src/action/reorg-cli.ts (with the src/core logic and js-yaml) into the single file design/actions/reorg.mjs,
// so the workflow template can be copied into <org>/.github without installing anything. `npm run build:action`
// writes it; tests/reorg-action.test.ts fails when the committed file is out of sync.
import { build } from 'vite';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const OUT = fileURLToPath(new URL('../design/actions/reorg.mjs', import.meta.url));
const HEADER = `#!/usr/bin/env node
// GENERATED by \`npm run build:action\` from src/action and src/core. Do not edit by hand.
// Used by design/actions/repo-groups-reorg.yml. Node 20+, no dependencies.
`;

export async function buildAction() {
  const out = await build({
    root,
    configFile: false,
    logLevel: 'silent',
    ssr: { noExternal: true, target: 'node' },
    build: {
      ssr: 'src/action/reorg-cli.ts',
      write: false,
      minify: false,
      target: 'node20',
      rollupOptions: { output: { format: 'es', codeSplitting: false, entryFileNames: 'reorg.mjs' } },
    },
  });
  const chunks = (Array.isArray(out) ? out[0] : out).output.filter((c) => c.type === 'chunk');
  if (chunks.length !== 1) throw new Error(`Expected one chunk, got ${chunks.length}`);
  return HEADER + chunks[0].code;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(OUT, await buildAction());
  console.log('Wrote design/actions/reorg.mjs');
}
